paths:
  #? the get product edpoint docummentation
  /api/v1/product/get-product:
    get:
      summary: Get Product endpoint
      description: This is endpoint it responsible for fetching product. It can fetch products by Id, name, price, inStock, category
      tags:
        - Product
      operationId: getProduct
      produces:
        - application/json
      parameters:
        - in: query
          name: id
          description: The ID of the product to be edited
          schema:
            type: integer
            example: 1
        - name: name
          in: query
          type: string
          description: The name of the id must be unique
        - name: category
          in: query
          type: string
          summary: Products category

        - name: price
          in: query
          type: integer
          summary: Products price

        - name: inStock
          in: query
          type: boolean
          summary: Products inStock

      responses:
        200:
          description: Successful product fetch
          content: application/json
          schema:
            example:
              status: sucess
              data:
                - name: test product
                  description: test description
                  category: book
                  price: 4000
                  inStock: true
                  createdAt: 2020-02-19T01:17:13.838Z
                  updatedAt: 2020-02-19T01:17:13.838Z
                - name: test product
                  description: test description
                  category: book
                  price: 4000
                  inStock: true
                  createdAt: 2020-02-19T01:17:13.838Z
                  updatedAt: 2020-02-19T01:17:13.838Z

        401:
          description: Unauthorized client
          content: application/json
          schema:
            example:
              status: error
              error: Not authorized to make this request, token is invalid or expired

  #? the add product edpoint docummentation
  /api/v1/product/add-product:
    post:
      summary: Add Product endpoint
      tags:
        - Product
      operationId: addProduct
      produces:
        - application/json
      parameters:
        - name: Authorization
          description: Bearer token
          in: header
          required: true
          type: string
          schema:
            type: string
            example: Bearer {Token}
        - name: name
          in: formData
          type: string
          required: true
          summary: Products name

        - name: description
          in: formData
          type: string
          required: true
          summary: Products description

        - name: category
          in: formData
          type: string
          required: true
          summary: Products category

        - name: price
          in: formData
          type: integer
          required: true
          summary: Products price

        - name: imageUrl
          in: formData
          type: string
          required: true
          summary: Products imageUrl

        - name: inStock
          in: formData
          type: boolean
          required: true
          summary: Products inStock

      responses:
        200:
          description: Successful product add
          content: application/json
          schema:
            example:
              status: sucess
              data:
                name: test product
                description: test description
                category: book
                price: 4000
                inStock: true
                createdAt: 2020-02-19T01:17:13.838Z
                updatedAt: 2020-02-19T01:17:13.838Z

        401:
          description: Unauthorized client
          content: application/json
          schema:
            example:
              status: error
              error: Not authorized to make this request, token is invalid or expired

  #? the edit product edpoint docummentation
  /api/v1/product/edit-product/{product_id}:
    put:
      summary: Edit Product endpoint
      tags:
        - Product
      operationId: editProduct
      produces:
        - application/json
      parameters:
        - name: Authorization
          description: Bearer token
          in: header
          required: true
          type: string
          schema:
            type: string
            example: Bearer {Token}
        - in: path
          name: product_id
          required: false
          schema:
            type: integer
            example: 23
            description: The ID of the product to be edited
        - name: name
          in: formData
          type: string
          required: false
          summary: Products name
          description: The name of the id must be unique

        - name: description
          in: formData
          type: string
          required: false
          summary: Products description

        - name: category
          in: formData
          type: string
          required: false
          summary: Products category

        - name: price
          in: formData
          type: integer
          required: false
          summary: Products price

        - name: imageUrl
          in: formData
          type: string
          required: false
          summary: Products imageUrl

        - name: inStock
          in: formData
          type: boolean
          required: true
          summary: Products inStock

      responses:
        200:
          description: Successful product edit
          content: application/json
          schema:
            example:
              status: sucess
              data:
                name: test product
                description: test description
                category: book
                price: 4000
                inStock: true
                createdAt: 2020-02-19T01:17:13.838Z
                updatedAt: 2020-02-19T01:17:13.838Z

        401:
          description: Unauthorized client
          content: application/json
          schema:
            example:
              status: error
              error: Not authorized to make this request, token is invalid or expired
        404:
          description: A user with the specified ID was not found.

  #? the delete product edpoint docummentation
  /api/v1/product/delete-product/{product_id}:
    delete:
      summary: delete Product endpoint
      tags:
        - Product
      operationId: deleteProduct
      produces:
        - application/json
      parameters:
        - name: Authorization
          description: Bearer token
          in: header
          required: true
          schema:
            type: string
            example: Bearer {token}
        - in: path
          name: product_id
          required: true
          schema:
            type: integer
            description: The ID of the product to be deleted

      responses:
        200:
          description: Successful product delete
          content: application/json
          schema:
            example:
              status: sucess
              data:
                deleted: true
                id: 12

        401:
          description: Unauthorized client
          content: application/json
          schema:
            example:
              status: error
              error: Not authorized to make this request, token is invalid or expired
        404:
          description: A user with the specified ID was not found.

definitions:
  Product:
    properties:
      id:
        type: integer
        example: 2
      name:
        type: string
        example: est product
      description:
        type: string
        example: test description
      category:
        type: string
        example: book
      price:
        type: integer
        example: 4000
      inStock:
        type: boolean
        example: true
      updatedAt:
        type: string
        example: 2020-02-19T01:17:13.838Z
      createdAt:
        type: string
        example: 2020-02-19T01:17:13.838Z
